### ISSUE TITLE
"Place" mixin

### ISSUE THREAD

**Issue by brob** [Snugug/griddle#1]
Part of the power of grid is being able to place items across both x and y axis. I'm not sure if this is a refactor of the span mixin or a new mixin on top of that, but I think having a full-featured "placement" mixin would be interesting.

I played with an implementation, but Sass doesn't dig on the Grid notation of `grid-column: start / end`

Potential Example output:
```
.placed-item {
        align-self: end; // Adds dynamic alignments to the grid item (default to stretch)
        grid-column: 1 / 3;
        grid-row: 1 / 2;
}
```

**Comment by Snugug** [comment]
The `span` mixins provide for both span and placement currently, but instead of using the `{{start}} / {{end}}` syntax used above, uses the `{{start}} / span {{amount}}` syntax. To accomplish what you've described above, you'd do the following:

```scss
.placed-item {
  @include span(2, 1); // Span 2 columns starting at the first column
  @include row-span(1, 1); // Span 1 column starting at the first column
  align-self: end;
}
```
Which would become
```scss
.placed-item {
  grid-column: 1 / span 2;
  grid-row: 1 / span 1;
  align-self: end;
}
```

Is there a specific need to use the `{{start}} / {{end}}` syntax over the `span` syntax here? In its current form, the `span` mixin won't accommodate negative grid line counting like the the former does, but that's likely a more advanced use of CSS Grid that you're going to want to write the actual syntax for.
